run:
  timeout: 10m
  tests: true
  build-tags:
    - netgo
    - ledger

linters:
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck

linters-settings:
  goimports:
    local-prefixes: github.com/paw

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

  gosec:
    excludes:
      - G107 # Url provided as taint input (common in blockchain apps)
      - G204 # Audit use of command execution (needed for CLI)

  stylecheck:
    checks: ['all', '-ST1003'] # Allow underscores in func names for test helpers

issues:
  exclude-dirs:
    - docs
    - proto
    - third_party
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - dupl
        - goconst

    # Exclude certain golangci-lint issues in autogenerated proto files
    - path: \.pb\.go$
      linters:
        - goimports
        - stylecheck

    # Ignore long lines in tests (table-driven tests can be long)
    - path: _test\.go
      linters:
        - lll

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  sort-results: true
