name: Feature Request
description: Suggest a new feature for PAW
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered

  - type: dropdown
    id: module
    attributes:
      label: Related Module
      options:
        - DEX
        - Compute
        - Oracle
        - IBC
        - Governance
        - Other
    validations:
      required: true
