{
  "global": {
    "severity": "medium",
    "confidence": "medium",
    "exclude_dir": [
      "testutil/",
      "tests/"
    ],
    "exclude_generated": true
  },
  "rules": {
    "G101": {
      "enabled": false
    },
    "G201": {
      "enabled": true
    },
    "G202": {
      "enabled": true
    },
    "G203": {
      "enabled": true
    },
    "G303": {
      "enabled": true
    },
    "G304": {
      "enabled": true
    },
    "G305": {
      "enabled": true
    },
    "G306": {
      "enabled": true
    },
    "G307": {
      "enabled": true
    },
    "G404": {
      "enabled": true
    },
    "G501": {
      "enabled": true
    },
    "G502": {
      "enabled": true
    },
    "G505": {
      "enabled": true
    },
    "G506": {
      "enabled": true
    },
    "G507": {
      "enabled": true
    },
    "G508": {
      "enabled": true
    },
    "G509": {
      "enabled": true
    }
  }
}
