// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: paw/compute/v1/compute.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the compute module.
type Params struct {
	// min_stake is the minimum stake required to register as a compute provider
	MinStake cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=min_stake,json=minStake,proto3,customtype=cosmossdk.io/math.Int" json:"min_stake"`
	// verification_timeout is the timeout for compute verification in seconds
	VerificationTimeout uint64 `protobuf:"varint,2,opt,name=verification_timeout,json=verificationTimeout,proto3" json:"verification_timeout,omitempty"`
	// max_retries is the maximum number of verification retries
	MaxRetries uint32 `protobuf:"varint,3,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_34e1fef9aade802d, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetVerificationTimeout() uint64 {
	if m != nil {
		return m.VerificationTimeout
	}
	return 0
}

func (m *Params) GetMaxRetries() uint32 {
	if m != nil {
		return m.MaxRetries
	}
	return 0
}

// ComputeTask represents a compute task submitted for verification
type ComputeTask struct {
	Id             uint64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Requester      string                `protobuf:"bytes,2,opt,name=requester,proto3" json:"requester,omitempty"`
	TaskType       string                `protobuf:"bytes,3,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	InputData      []byte                `protobuf:"bytes,4,opt,name=input_data,json=inputData,proto3" json:"input_data,omitempty"`
	ExpectedOutput []byte                `protobuf:"bytes,5,opt,name=expected_output,json=expectedOutput,proto3" json:"expected_output,omitempty"`
	Reward         cosmossdk_io_math.Int `protobuf:"bytes,6,opt,name=reward,proto3,customtype=cosmossdk.io/math.Int" json:"reward"`
	Status         string                `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt      int64                 `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	VerifiedAt     int64                 `protobuf:"varint,9,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
}

func (m *ComputeTask) Reset()         { *m = ComputeTask{} }
func (m *ComputeTask) String() string { return proto.CompactTextString(m) }
func (*ComputeTask) ProtoMessage()    {}
func (*ComputeTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_34e1fef9aade802d, []int{1}
}
func (m *ComputeTask) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ComputeTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ComputeTask.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ComputeTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeTask.Merge(m, src)
}
func (m *ComputeTask) XXX_Size() int {
	return m.Size()
}
func (m *ComputeTask) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeTask.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeTask proto.InternalMessageInfo

func (m *ComputeTask) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ComputeTask) GetRequester() string {
	if m != nil {
		return m.Requester
	}
	return ""
}

func (m *ComputeTask) GetTaskType() string {
	if m != nil {
		return m.TaskType
	}
	return ""
}

func (m *ComputeTask) GetInputData() []byte {
	if m != nil {
		return m.InputData
	}
	return nil
}

func (m *ComputeTask) GetExpectedOutput() []byte {
	if m != nil {
		return m.ExpectedOutput
	}
	return nil
}

func (m *ComputeTask) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ComputeTask) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *ComputeTask) GetVerifiedAt() int64 {
	if m != nil {
		return m.VerifiedAt
	}
	return 0
}

// GenesisState defines the compute module's genesis state.
type GenesisState struct {
	Params     Params        `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Tasks      []ComputeTask `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks"`
	NextTaskId uint64        `protobuf:"varint,3,opt,name=next_task_id,json=nextTaskId,proto3" json:"next_task_id,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_34e1fef9aade802d, []int{2}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetTasks() []ComputeTask {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *GenesisState) GetNextTaskId() uint64 {
	if m != nil {
		return m.NextTaskId
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "paw.compute.v1.Params")
	proto.RegisterType((*ComputeTask)(nil), "paw.compute.v1.ComputeTask")
	proto.RegisterType((*GenesisState)(nil), "paw.compute.v1.GenesisState")
}

func init() { proto.RegisterFile("paw/compute/v1/compute.proto", fileDescriptor_34e1fef9aade802d) }

var fileDescriptor_34e1fef9aade802d = []byte{
	// 623 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xc7, 0x63, 0x27, 0xcd, 0xaf, 0xde, 0xe4, 0x17, 0xd0, 0x52, 0x2a, 0xd3, 0x42, 0x6a, 0xf5,
	0x42, 0x24, 0x54, 0x47, 0x2e, 0x08, 0xa4, 0x70, 0x6a, 0x8a, 0x54, 0x7a, 0x40, 0x58, 0x6e, 0x55,
	0x21, 0x54, 0xc9, 0x9a, 0xda, 0x4b, 0xba, 0x8a, 0xfc, 0x07, 0xef, 0x38, 0x49, 0xdf, 0x82, 0x37,
	0x40, 0xe2, 0xc0, 0x81, 0x73, 0xdf, 0x81, 0x8a, 0x53, 0xd5, 0x0b, 0x88, 0x43, 0x85, 0xd2, 0x1b,
	0x4f, 0x81, 0x76, 0xed, 0x88, 0xa6, 0x37, 0x6e, 0xe3, 0xcf, 0xf7, 0x3b, 0x9e, 0xd9, 0xd9, 0x59,
	0x72, 0x3f, 0x85, 0x71, 0x37, 0x48, 0xa2, 0x34, 0x47, 0xd6, 0x1d, 0x39, 0xb3, 0xd0, 0x4e, 0xb3,
	0x04, 0x13, 0xda, 0x4a, 0x61, 0x6c, 0xcf, 0xd0, 0xc8, 0x59, 0x59, 0x1a, 0x24, 0x83, 0x44, 0x49,
	0x5d, 0x19, 0x15, 0xae, 0x95, 0x7b, 0x41, 0x22, 0xa2, 0x44, 0xf8, 0x85, 0x50, 0x7c, 0x14, 0xd2,
	0xfa, 0x67, 0x8d, 0xd4, 0x5d, 0xc8, 0x20, 0x12, 0xf4, 0x25, 0x31, 0x22, 0x1e, 0xfb, 0x02, 0x61,
	0xc8, 0x4c, 0xcd, 0xd2, 0x3a, 0x46, 0xff, 0xd1, 0xd9, 0xe5, 0x5a, 0xe5, 0xe7, 0xe5, 0xda, 0xdd,
	0x22, 0x47, 0x84, 0x43, 0x9b, 0x27, 0xdd, 0x08, 0xf0, 0xd8, 0xde, 0x8d, 0xf1, 0xe2, 0x74, 0x83,
	0x94, 0x3f, 0xdb, 0x8d, 0xd1, 0x5b, 0x8c, 0x78, 0xbc, 0x27, 0x93, 0xa9, 0x43, 0x96, 0x46, 0x2c,
	0xe3, 0xef, 0x78, 0x00, 0xc8, 0x93, 0xd8, 0x47, 0x1e, 0xb1, 0x24, 0x47, 0x53, 0xb7, 0xb4, 0x4e,
	0xcd, 0xbb, 0x73, 0x5d, 0xdb, 0x2f, 0x24, 0xba, 0x46, 0x1a, 0x11, 0x4c, 0xfc, 0x8c, 0x61, 0xc6,
	0x99, 0x30, 0xab, 0x96, 0xd6, 0xf9, 0xdf, 0x23, 0x11, 0x4c, 0xbc, 0x82, 0xac, 0x7f, 0xd7, 0x49,
	0x63, 0xbb, 0x38, 0xe8, 0x3e, 0x88, 0x21, 0x6d, 0x11, 0x9d, 0x87, 0xaa, 0xcd, 0x9a, 0xa7, 0xf3,
	0x90, 0x3e, 0x25, 0x46, 0xc6, 0xde, 0xe7, 0x4c, 0x20, 0xcb, 0x54, 0x21, 0xa3, 0x6f, 0x5e, 0x9c,
	0x6e, 0x2c, 0x95, 0x0d, 0x6e, 0x85, 0x61, 0xc6, 0x84, 0xd8, 0xc3, 0x8c, 0xc7, 0x03, 0xef, 0xaf,
	0x95, 0xae, 0x12, 0x03, 0x41, 0x0c, 0x7d, 0x3c, 0x49, 0x99, 0x2a, 0x6b, 0x78, 0x8b, 0x12, 0xec,
	0x9f, 0xa4, 0x8c, 0x3e, 0x20, 0x84, 0xc7, 0x69, 0x8e, 0x7e, 0x08, 0x08, 0x66, 0xcd, 0xd2, 0x3a,
	0x4d, 0xcf, 0x50, 0xe4, 0x05, 0x20, 0xd0, 0x87, 0xe4, 0x16, 0x9b, 0xa4, 0x2c, 0x40, 0x16, 0xfa,
	0x49, 0x8e, 0x69, 0x8e, 0xe6, 0x82, 0xf2, 0xb4, 0x66, 0xf8, 0xb5, 0xa2, 0x74, 0x9b, 0xd4, 0x33,
	0x36, 0x86, 0x2c, 0x34, 0xeb, 0xff, 0x3e, 0xd7, 0x32, 0x95, 0x2e, 0x93, 0xba, 0x40, 0xc0, 0x5c,
	0x98, 0xff, 0xa9, 0x36, 0xcb, 0x2f, 0xd9, 0x64, 0x90, 0x31, 0x90, 0x4d, 0x00, 0x9a, 0x8b, 0x96,
	0xd6, 0xa9, 0x7a, 0x46, 0x49, 0xb6, 0xd4, 0x64, 0x8b, 0x81, 0x17, 0xba, 0xa1, 0x74, 0x32, 0x43,
	0x5b, 0xb8, 0xfe, 0x51, 0x23, 0xcd, 0x1d, 0x16, 0x33, 0xc1, 0xc5, 0x1e, 0x02, 0x32, 0xfa, 0x84,
	0xd4, 0x53, 0xb5, 0x12, 0x6a, 0xbc, 0x8d, 0xcd, 0x65, 0x7b, 0x7e, 0xcb, 0xec, 0x62, 0x61, 0xfa,
	0x35, 0x79, 0x0a, 0xaf, 0xf4, 0xd2, 0x67, 0x64, 0x41, 0xce, 0x4d, 0x98, 0xba, 0x55, 0xed, 0x34,
	0x36, 0x57, 0x6f, 0x26, 0x5d, 0xbb, 0xbc, 0x32, 0xb3, 0xf0, 0x53, 0x8b, 0x34, 0x63, 0x36, 0x41,
	0x5f, 0x5d, 0x03, 0x0f, 0xd5, 0x25, 0xd4, 0x3c, 0x22, 0x99, 0x34, 0xef, 0x86, 0xfd, 0xaf, 0xda,
	0xd9, 0xb4, 0xad, 0x9d, 0x4f, 0xdb, 0xda, 0xaf, 0x69, 0x5b, 0xfb, 0x70, 0xd5, 0xae, 0x9c, 0x5f,
	0xb5, 0x2b, 0x3f, 0xae, 0xda, 0x15, 0x42, 0x83, 0x24, 0xba, 0x51, 0xa9, 0xdf, 0x2c, 0x4b, 0xb9,
	0x72, 0xc3, 0x5d, 0xed, 0xad, 0x33, 0xe0, 0x78, 0x9c, 0x1f, 0x49, 0x4b, 0x37, 0x85, 0xf1, 0x46,
	0x70, 0x0c, 0x3c, 0x96, 0x51, 0x77, 0xfe, 0x6d, 0x3d, 0x2f, 0xc3, 0x91, 0xf3, 0x49, 0xaf, 0xba,
	0xdb, 0x6f, 0xbe, 0xe8, 0x2d, 0x17, 0xc6, 0xb3, 0xc6, 0xed, 0x03, 0xe7, 0x9b, 0x02, 0x87, 0x25,
	0x38, 0x3c, 0x70, 0xa6, 0xfa, 0xca, 0x3c, 0x38, 0xdc, 0x71, 0xfb, 0xaf, 0x18, 0x82, 0xdc, 0x97,
	0xdf, 0xfa, 0x6d, 0x17, 0xc6, 0xbd, 0x5e, 0xa9, 0xf6, 0x7a, 0x07, 0xce, 0x51, 0x5d, 0xbd, 0xba,
	0xc7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe4, 0xe5, 0x2e, 0x1b, 0xd6, 0x03, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxRetries != 0 {
		i = encodeVarintCompute(dAtA, i, uint64(m.MaxRetries))
		i--
		dAtA[i] = 0x18
	}
	if m.VerificationTimeout != 0 {
		i = encodeVarintCompute(dAtA, i, uint64(m.VerificationTimeout))
		i--
		dAtA[i] = 0x10
	}
	{
		size := m.MinStake.Size()
		i -= size
		if _, err := m.MinStake.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCompute(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ComputeTask) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ComputeTask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ComputeTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.VerifiedAt != 0 {
		i = encodeVarintCompute(dAtA, i, uint64(m.VerifiedAt))
		i--
		dAtA[i] = 0x48
	}
	if m.CreatedAt != 0 {
		i = encodeVarintCompute(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x40
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintCompute(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x3a
	}
	{
		size := m.Reward.Size()
		i -= size
		if _, err := m.Reward.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCompute(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.ExpectedOutput) > 0 {
		i -= len(m.ExpectedOutput)
		copy(dAtA[i:], m.ExpectedOutput)
		i = encodeVarintCompute(dAtA, i, uint64(len(m.ExpectedOutput)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.InputData) > 0 {
		i -= len(m.InputData)
		copy(dAtA[i:], m.InputData)
		i = encodeVarintCompute(dAtA, i, uint64(len(m.InputData)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.TaskType) > 0 {
		i -= len(m.TaskType)
		copy(dAtA[i:], m.TaskType)
		i = encodeVarintCompute(dAtA, i, uint64(len(m.TaskType)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Requester) > 0 {
		i -= len(m.Requester)
		copy(dAtA[i:], m.Requester)
		i = encodeVarintCompute(dAtA, i, uint64(len(m.Requester)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintCompute(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NextTaskId != 0 {
		i = encodeVarintCompute(dAtA, i, uint64(m.NextTaskId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Tasks) > 0 {
		for iNdEx := len(m.Tasks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Tasks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCompute(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintCompute(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintCompute(dAtA []byte, offset int, v uint64) int {
	offset -= sovCompute(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MinStake.Size()
	n += 1 + l + sovCompute(uint64(l))
	if m.VerificationTimeout != 0 {
		n += 1 + sovCompute(uint64(m.VerificationTimeout))
	}
	if m.MaxRetries != 0 {
		n += 1 + sovCompute(uint64(m.MaxRetries))
	}
	return n
}

func (m *ComputeTask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovCompute(uint64(m.Id))
	}
	l = len(m.Requester)
	if l > 0 {
		n += 1 + l + sovCompute(uint64(l))
	}
	l = len(m.TaskType)
	if l > 0 {
		n += 1 + l + sovCompute(uint64(l))
	}
	l = len(m.InputData)
	if l > 0 {
		n += 1 + l + sovCompute(uint64(l))
	}
	l = len(m.ExpectedOutput)
	if l > 0 {
		n += 1 + l + sovCompute(uint64(l))
	}
	l = m.Reward.Size()
	n += 1 + l + sovCompute(uint64(l))
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovCompute(uint64(l))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovCompute(uint64(m.CreatedAt))
	}
	if m.VerifiedAt != 0 {
		n += 1 + sovCompute(uint64(m.VerifiedAt))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovCompute(uint64(l))
	if len(m.Tasks) > 0 {
		for _, e := range m.Tasks {
			l = e.Size()
			n += 1 + l + sovCompute(uint64(l))
		}
	}
	if m.NextTaskId != 0 {
		n += 1 + sovCompute(uint64(m.NextTaskId))
	}
	return n
}

func sovCompute(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCompute(x uint64) (n int) {
	return sovCompute(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCompute
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinStake", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCompute
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCompute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinStake.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerificationTimeout", wireType)
			}
			m.VerificationTimeout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VerificationTimeout |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxRetries", wireType)
			}
			m.MaxRetries = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxRetries |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCompute(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCompute
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ComputeTask) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCompute
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ComputeTask: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ComputeTask: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Requester", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCompute
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCompute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Requester = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCompute
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCompute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InputData", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCompute
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCompute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InputData = append(m.InputData[:0], dAtA[iNdEx:postIndex]...)
			if m.InputData == nil {
				m.InputData = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpectedOutput", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCompute
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCompute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExpectedOutput = append(m.ExpectedOutput[:0], dAtA[iNdEx:postIndex]...)
			if m.ExpectedOutput == nil {
				m.ExpectedOutput = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reward", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCompute
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCompute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Reward.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCompute
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCompute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifiedAt", wireType)
			}
			m.VerifiedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VerifiedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCompute(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCompute
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCompute
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCompute
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCompute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tasks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCompute
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCompute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tasks = append(m.Tasks, ComputeTask{})
			if err := m.Tasks[len(m.Tasks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextTaskId", wireType)
			}
			m.NextTaskId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextTaskId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCompute(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCompute
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCompute(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCompute
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCompute
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCompute
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCompute
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCompute
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCompute
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCompute        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCompute          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCompute = fmt.Errorf("proto: unexpected end of group")
)
