// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: paw/oracle/v1/oracle.proto

package types

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	cosmossdk_io_math "cosmossdk.io/math"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the oracle module.
type Params struct {
	// min_validators is the minimum number of validators required for a price feed
	MinValidators uint32 `protobuf:"varint,1,opt,name=min_validators,json=minValidators,proto3" json:"min_validators,omitempty"`
	// update_interval is the minimum interval between price updates in seconds
	UpdateInterval uint64 `protobuf:"varint,2,opt,name=update_interval,json=updateInterval,proto3" json:"update_interval,omitempty"`
	// expiry_duration is how long a price is considered valid in seconds
	ExpiryDuration uint64 `protobuf:"varint,3,opt,name=expiry_duration,json=expiryDuration,proto3" json:"expiry_duration,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_12b0d32940c9cc63, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMinValidators() uint32 {
	if m != nil {
		return m.MinValidators
	}
	return 0
}

func (m *Params) GetUpdateInterval() uint64 {
	if m != nil {
		return m.UpdateInterval
	}
	return 0
}

func (m *Params) GetExpiryDuration() uint64 {
	if m != nil {
		return m.ExpiryDuration
	}
	return 0
}

// PriceFeed represents a price feed for an asset
type PriceFeed struct {
	Asset      string                      `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	Price      cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=price,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"price"`
	Timestamp  int64                       `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Validators []string                    `protobuf:"bytes,4,rep,name=validators,proto3" json:"validators,omitempty"`
}

func (m *PriceFeed) Reset()         { *m = PriceFeed{} }
func (m *PriceFeed) String() string { return proto.CompactTextString(m) }
func (*PriceFeed) ProtoMessage()    {}
func (*PriceFeed) Descriptor() ([]byte, []int) {
	return fileDescriptor_12b0d32940c9cc63, []int{1}
}
func (m *PriceFeed) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PriceFeed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PriceFeed.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PriceFeed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceFeed.Merge(m, src)
}
func (m *PriceFeed) XXX_Size() int {
	return m.Size()
}
func (m *PriceFeed) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceFeed.DiscardUnknown(m)
}

var xxx_messageInfo_PriceFeed proto.InternalMessageInfo

func (m *PriceFeed) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *PriceFeed) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *PriceFeed) GetValidators() []string {
	if m != nil {
		return m.Validators
	}
	return nil
}

// GenesisState defines the oracle module's genesis state.
type GenesisState struct {
	Params     Params      `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	PriceFeeds []PriceFeed `protobuf:"bytes,2,rep,name=price_feeds,json=priceFeeds,proto3" json:"price_feeds"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_12b0d32940c9cc63, []int{2}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetPriceFeeds() []PriceFeed {
	if m != nil {
		return m.PriceFeeds
	}
	return nil
}

func init() {
	proto.RegisterType((*Params)(nil), "paw.oracle.v1.Params")
	proto.RegisterType((*PriceFeed)(nil), "paw.oracle.v1.PriceFeed")
	proto.RegisterType((*GenesisState)(nil), "paw.oracle.v1.GenesisState")
}

func init() { proto.RegisterFile("paw/oracle/v1/oracle.proto", fileDescriptor_12b0d32940c9cc63) }

var fileDescriptor_12b0d32940c9cc63 = []byte{
	// 497 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0x41, 0x8b, 0xd3, 0x40,
	0x14, 0xc7, 0x3b, 0x69, 0xb7, 0xd0, 0xa9, 0xdd, 0xc5, 0xb0, 0x42, 0xb7, 0x4a, 0xb6, 0x14, 0xc4,
	0x5e, 0x36, 0x21, 0xbb, 0xb7, 0x7a, 0x10, 0x42, 0xb1, 0x08, 0xca, 0x86, 0x08, 0x45, 0xa4, 0x10,
	0xde, 0x26, 0x63, 0x3b, 0xd8, 0x64, 0x86, 0xcc, 0x34, 0x71, 0x8f, 0x82, 0x1f, 0xc0, 0xcf, 0xe0,
	0x49, 0x3c, 0x7b, 0xf7, 0xba, 0x78, 0x5a, 0x3c, 0x89, 0x87, 0x45, 0xda, 0x9b, 0x9f, 0x42, 0x32,
	0x93, 0xd5, 0xed, 0xde, 0xde, 0xff, 0xf7, 0xfe, 0x6f, 0xe6, 0xbd, 0x37, 0x83, 0x7b, 0x1c, 0x0a,
	0x87, 0x65, 0x10, 0x2d, 0x89, 0x93, 0xbb, 0x55, 0x64, 0xf3, 0x8c, 0x49, 0x66, 0x76, 0x38, 0x14,
	0x76, 0x45, 0x72, 0xb7, 0xb7, 0x3f, 0x67, 0x73, 0xa6, 0x32, 0x4e, 0x19, 0x69, 0x53, 0xef, 0x20,
	0x62, 0x22, 0x61, 0x22, 0xd4, 0x09, 0x2d, 0x74, 0x6a, 0xf0, 0x1e, 0xe1, 0xa6, 0x0f, 0x19, 0x24,
	0xc2, 0x7c, 0x88, 0x77, 0x13, 0x9a, 0x86, 0x39, 0x2c, 0x69, 0x0c, 0x92, 0x65, 0xa2, 0x8b, 0xfa,
	0x68, 0xd8, 0x09, 0x3a, 0x09, 0x4d, 0xa7, 0xff, 0xa0, 0xf9, 0x08, 0xef, 0xad, 0x78, 0x0c, 0x92,
	0x84, 0x34, 0x95, 0x24, 0xcb, 0x61, 0xd9, 0x35, 0xfa, 0x68, 0xd8, 0x08, 0x76, 0x35, 0x7e, 0x56,
	0xd1, 0xd2, 0x48, 0xde, 0x71, 0x9a, 0x9d, 0x87, 0xf1, 0x2a, 0x03, 0x49, 0x59, 0xda, 0xad, 0x6b,
	0xa3, 0xc6, 0xe3, 0x8a, 0x0e, 0x3e, 0x23, 0xdc, 0xf2, 0x33, 0x1a, 0x91, 0xa7, 0x84, 0xc4, 0xe6,
	0x3e, 0xde, 0x01, 0x21, 0x88, 0x54, 0xb7, 0xb7, 0x02, 0x2d, 0xcc, 0x09, 0xde, 0xe1, 0xa5, 0x45,
	0xdd, 0xd5, 0xf2, 0xdc, 0x8b, 0xab, 0xc3, 0xda, 0xaf, 0xab, 0xc3, 0xfb, 0x7a, 0x18, 0x11, 0xbf,
	0xb5, 0x29, 0x73, 0x12, 0x90, 0x0b, 0xfb, 0x39, 0x99, 0x43, 0x74, 0x3e, 0x26, 0xd1, 0x8f, 0xaf,
	0x47, 0xb8, 0x9a, 0x75, 0x4c, 0xa2, 0x40, 0xd7, 0x9b, 0x0f, 0x70, 0x4b, 0xd2, 0x84, 0x08, 0x09,
	0x09, 0x57, 0xfd, 0xd4, 0x83, 0xff, 0xc0, 0xb4, 0x30, 0xbe, 0x31, 0x7f, 0xa3, 0x5f, 0x1f, 0xb6,
	0x82, 0x1b, 0x64, 0xf0, 0x01, 0xe1, 0x3b, 0x13, 0x92, 0x12, 0x41, 0xc5, 0x4b, 0x09, 0x92, 0x98,
	0x27, 0xb8, 0xc9, 0xd5, 0xfa, 0x54, 0xbb, 0xed, 0xe3, 0x7b, 0xf6, 0xd6, 0x83, 0xd8, 0x7a, 0xb7,
	0x5e, 0xa3, 0xec, 0x37, 0xa8, 0xac, 0xe6, 0x13, 0xdc, 0x56, 0xcd, 0x84, 0x6f, 0x08, 0x89, 0x45,
	0xd7, 0xe8, 0xd7, 0x87, 0xed, 0xe3, 0xee, 0xed, 0xca, 0xeb, 0x8d, 0x54, 0xc5, 0x98, 0x5f, 0x03,
	0xe1, 0x7d, 0x43, 0x17, 0x6b, 0x0b, 0x5d, 0xae, 0x2d, 0xf4, 0x7b, 0x6d, 0xa1, 0x8f, 0x1b, 0xab,
	0x76, 0xb9, 0xb1, 0x6a, 0x3f, 0x37, 0x56, 0x0d, 0xdf, 0x8d, 0x58, 0xb2, 0x7d, 0x92, 0xd7, 0x3e,
	0x55, 0xa1, 0x5f, 0x3e, 0xb8, 0x8f, 0x5e, 0x3b, 0x73, 0x2a, 0x17, 0xab, 0x33, 0x3b, 0x62, 0x89,
	0xc3, 0xa1, 0x38, 0x8a, 0x16, 0x40, 0xd3, 0x32, 0x72, 0xb6, 0xfe, 0xd9, 0x63, 0x1d, 0xe5, 0xee,
	0x27, 0xa3, 0xee, 0x9f, 0xbe, 0xfa, 0x62, 0x74, 0x7c, 0x28, 0x6c, 0x7d, 0x94, 0x3d, 0x75, 0xbf,
	0x2b, 0x3d, 0xd3, 0x7a, 0x36, 0x75, 0xd7, 0xc6, 0xc1, 0x96, 0x9e, 0x4d, 0x7c, 0xef, 0x05, 0x91,
	0x10, 0x83, 0x84, 0x3f, 0xc6, 0x9e, 0x0f, 0xc5, 0x68, 0xa4, 0x93, 0xa3, 0xd1, 0xd4, 0x3d, 0x6b,
	0xaa, 0xef, 0x77, 0xf2, 0x37, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x11, 0x98, 0xd1, 0xdc, 0x02, 0x00,
	0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExpiryDuration != 0 {
		i = encodeVarintOracle(dAtA, i, uint64(m.ExpiryDuration))
		i--
		dAtA[i] = 0x18
	}
	if m.UpdateInterval != 0 {
		i = encodeVarintOracle(dAtA, i, uint64(m.UpdateInterval))
		i--
		dAtA[i] = 0x10
	}
	if m.MinValidators != 0 {
		i = encodeVarintOracle(dAtA, i, uint64(m.MinValidators))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PriceFeed) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PriceFeed) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PriceFeed) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Validators) > 0 {
		for iNdEx := len(m.Validators) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Validators[iNdEx])
			copy(dAtA[i:], m.Validators[iNdEx])
			i = encodeVarintOracle(dAtA, i, uint64(len(m.Validators[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if m.Timestamp != 0 {
		i = encodeVarintOracle(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x18
	}
	{
		size := m.Price.Size()
		i -= size
		if _, err := m.Price.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintOracle(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Asset) > 0 {
		i -= len(m.Asset)
		copy(dAtA[i:], m.Asset)
		i = encodeVarintOracle(dAtA, i, uint64(len(m.Asset)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PriceFeeds) > 0 {
		for iNdEx := len(m.PriceFeeds) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PriceFeeds[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintOracle(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintOracle(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintOracle(dAtA []byte, offset int, v uint64) int {
	offset -= sovOracle(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MinValidators != 0 {
		n += 1 + sovOracle(uint64(m.MinValidators))
	}
	if m.UpdateInterval != 0 {
		n += 1 + sovOracle(uint64(m.UpdateInterval))
	}
	if m.ExpiryDuration != 0 {
		n += 1 + sovOracle(uint64(m.ExpiryDuration))
	}
	return n
}

func (m *PriceFeed) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Asset)
	if l > 0 {
		n += 1 + l + sovOracle(uint64(l))
	}
	l = m.Price.Size()
	n += 1 + l + sovOracle(uint64(l))
	if m.Timestamp != 0 {
		n += 1 + sovOracle(uint64(m.Timestamp))
	}
	if len(m.Validators) > 0 {
		for _, s := range m.Validators {
			l = len(s)
			n += 1 + l + sovOracle(uint64(l))
		}
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovOracle(uint64(l))
	if len(m.PriceFeeds) > 0 {
		for _, e := range m.PriceFeeds {
			l = e.Size()
			n += 1 + l + sovOracle(uint64(l))
		}
	}
	return n
}

func sovOracle(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozOracle(x uint64) (n int) {
	return sovOracle(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOracle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinValidators", wireType)
			}
			m.MinValidators = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinValidators |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateInterval", wireType)
			}
			m.UpdateInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdateInterval |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiryDuration", wireType)
			}
			m.ExpiryDuration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiryDuration |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipOracle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOracle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PriceFeed) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOracle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PriceFeed: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PriceFeed: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOracle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOracle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Asset = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOracle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOracle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validators", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOracle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOracle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validators = append(m.Validators, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOracle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOracle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOracle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOracle
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOracle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriceFeeds", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOracle
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOracle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PriceFeeds = append(m.PriceFeeds, PriceFeed{})
			if err := m.PriceFeeds[len(m.PriceFeeds)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOracle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOracle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipOracle(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOracle
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthOracle
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupOracle
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthOracle
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthOracle        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOracle          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupOracle = fmt.Errorf("proto: unexpected end of group")
)
