// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: paw/oracle/v1/oracle.proto

package types

import (
	math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf

// Params defines the parameters for the oracle module.
type Params struct {
	VotePeriod         uint64         `protobuf:"varint,1,opt,name=vote_period,json=votePeriod,proto3" json:"vote_period,omitempty"`
	VoteThreshold      math.LegacyDec `protobuf:"bytes,2,opt,name=vote_threshold,json=voteThreshold,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"vote_threshold"`
	SlashFraction      math.LegacyDec `protobuf:"bytes,3,opt,name=slash_fraction,json=slashFraction,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"slash_fraction"`
	SlashWindow        uint64         `protobuf:"varint,4,opt,name=slash_window,json=slashWindow,proto3" json:"slash_window,omitempty"`
	MinValidPerWindow  uint64         `protobuf:"varint,5,opt,name=min_valid_per_window,json=minValidPerWindow,proto3" json:"min_valid_per_window,omitempty"`
	TwapLookbackWindow uint64         `protobuf:"varint,6,opt,name=twap_lookback_window,json=twapLookbackWindow,proto3" json:"twap_lookback_window,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	return 0, nil
}

func (m *Params) Size() (n int) {
	return 0
}

func (m *Params) Unmarshal(dAtA []byte) error {
	return nil
}

// Price represents the aggregated price for an asset
type Price struct {
	Asset         string         `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	Price         math.LegacyDec `protobuf:"bytes,2,opt,name=price,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"price"`
	BlockHeight   int64          `protobuf:"varint,3,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	BlockTime     int64          `protobuf:"varint,4,opt,name=block_time,json=blockTime,proto3" json:"block_time,omitempty"`
	NumValidators uint32         `protobuf:"varint,5,opt,name=num_validators,json=numValidators,proto3" json:"num_validators,omitempty"`
}

func (m *Price) Reset()         { *m = Price{} }
func (m *Price) String() string { return proto.CompactTextString(m) }
func (*Price) ProtoMessage()    {}

func (m *Price) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Price) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Price) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	return 0, nil
}

func (m *Price) Size() (n int) {
	return 0
}

func (m *Price) Unmarshal(dAtA []byte) error {
	return nil
}

// ValidatorPrice represents a price submission by a validator
type ValidatorPrice struct {
	ValidatorAddr string         `protobuf:"bytes,1,opt,name=validator_addr,json=validatorAddr,proto3" json:"validator_addr,omitempty"`
	Asset         string         `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	Price         math.LegacyDec `protobuf:"bytes,3,opt,name=price,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"price"`
	BlockHeight   int64          `protobuf:"varint,4,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	VotingPower   int64          `protobuf:"varint,5,opt,name=voting_power,json=votingPower,proto3" json:"voting_power,omitempty"`
}

func (m *ValidatorPrice) Reset()         { *m = ValidatorPrice{} }
func (m *ValidatorPrice) String() string { return proto.CompactTextString(m) }
func (*ValidatorPrice) ProtoMessage()    {}

func (m *ValidatorPrice) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorPrice) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorPrice) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	return 0, nil
}

func (m *ValidatorPrice) Size() (n int) {
	return 0
}

func (m *ValidatorPrice) Unmarshal(dAtA []byte) error {
	return nil
}

// ValidatorOracle represents oracle information for a validator
type ValidatorOracle struct {
	ValidatorAddr    string `protobuf:"bytes,1,opt,name=validator_addr,json=validatorAddr,proto3" json:"validator_addr,omitempty"`
	MissCounter      uint64 `protobuf:"varint,2,opt,name=miss_counter,json=missCounter,proto3" json:"miss_counter,omitempty"`
	TotalSubmissions uint64 `protobuf:"varint,3,opt,name=total_submissions,json=totalSubmissions,proto3" json:"total_submissions,omitempty"`
	IsActive         bool   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
}

func (m *ValidatorOracle) Reset()         { *m = ValidatorOracle{} }
func (m *ValidatorOracle) String() string { return proto.CompactTextString(m) }
func (*ValidatorOracle) ProtoMessage()    {}

func (m *ValidatorOracle) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorOracle) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorOracle) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	return 0, nil
}

func (m *ValidatorOracle) Size() (n int) {
	return 0
}

func (m *ValidatorOracle) Unmarshal(dAtA []byte) error {
	return nil
}

// PriceSnapshot represents a historical price snapshot for TWAP
type PriceSnapshot struct {
	Asset       string         `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	Price       math.LegacyDec `protobuf:"bytes,2,opt,name=price,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"price"`
	BlockHeight int64          `protobuf:"varint,3,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	BlockTime   int64          `protobuf:"varint,4,opt,name=block_time,json=blockTime,proto3" json:"block_time,omitempty"`
}

func (m *PriceSnapshot) Reset()         { *m = PriceSnapshot{} }
func (m *PriceSnapshot) String() string { return proto.CompactTextString(m) }
func (*PriceSnapshot) ProtoMessage()    {}

func (m *PriceSnapshot) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PriceSnapshot) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PriceSnapshot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	return 0, nil
}

func (m *PriceSnapshot) Size() (n int) {
	return 0
}

func (m *PriceSnapshot) Unmarshal(dAtA []byte) error {
	return nil
}

// GenesisState defines the oracle module's genesis state.
type GenesisState struct {
	Params           Params            `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Prices           []Price           `protobuf:"bytes,2,rep,name=prices,proto3" json:"prices"`
	ValidatorPrices  []ValidatorPrice  `protobuf:"bytes,3,rep,name=validator_prices,json=validatorPrices,proto3" json:"validator_prices"`
	ValidatorOracles []ValidatorOracle `protobuf:"bytes,4,rep,name=validator_oracles,json=validatorOracles,proto3" json:"validator_oracles"`
	PriceSnapshots   []PriceSnapshot   `protobuf:"bytes,5,rep,name=price_snapshots,json=priceSnapshots,proto3" json:"price_snapshots"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	return 0, nil
}

func (m *GenesisState) Size() (n int) {
	return 0
}

func (m *GenesisState) Unmarshal(dAtA []byte) error {
	return nil
}

func init() {
	proto.RegisterType((*Params)(nil), "paw.oracle.v1.Params")
	proto.RegisterType((*Price)(nil), "paw.oracle.v1.Price")
	proto.RegisterType((*ValidatorPrice)(nil), "paw.oracle.v1.ValidatorPrice")
	proto.RegisterType((*ValidatorOracle)(nil), "paw.oracle.v1.ValidatorOracle")
	proto.RegisterType((*PriceSnapshot)(nil), "paw.oracle.v1.PriceSnapshot")
	proto.RegisterType((*GenesisState)(nil), "paw.oracle.v1.GenesisState")
}
