// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: paw/oracle/v1/state.proto

package types

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// CircuitBreakerState defines the serialized form of the oracle circuit breaker.
type CircuitBreakerState struct {
	Active       bool   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	TriggeredBy  string `protobuf:"bytes,2,opt,name=triggered_by,json=triggeredBy,proto3" json:"triggered_by,omitempty"`
	Reason       string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	BlockHeight  int64  `protobuf:"varint,4,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	RecoveryTime int64  `protobuf:"varint,5,opt,name=recovery_time,json=recoveryTime,proto3" json:"recovery_time,omitempty"`
}

func (m *CircuitBreakerState) Reset()         { *m = CircuitBreakerState{} }
func (m *CircuitBreakerState) String() string { return proto.CompactTextString(m) }
func (*CircuitBreakerState) ProtoMessage()    {}
func (*CircuitBreakerState) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bc0ab4b4862cbcd, []int{0}
}
func (m *CircuitBreakerState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CircuitBreakerState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CircuitBreakerState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CircuitBreakerState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CircuitBreakerState.Merge(m, src)
}
func (m *CircuitBreakerState) XXX_Size() int {
	return m.Size()
}
func (m *CircuitBreakerState) XXX_DiscardUnknown() {
	xxx_messageInfo_CircuitBreakerState.DiscardUnknown(m)
}

var xxx_messageInfo_CircuitBreakerState proto.InternalMessageInfo

func (m *CircuitBreakerState) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *CircuitBreakerState) GetTriggeredBy() string {
	if m != nil {
		return m.TriggeredBy
	}
	return ""
}

func (m *CircuitBreakerState) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *CircuitBreakerState) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *CircuitBreakerState) GetRecoveryTime() int64 {
	if m != nil {
		return m.RecoveryTime
	}
	return 0
}

// EmergencyPauseState tracks the emergency pause status of the Oracle module
type EmergencyPauseState struct {
	// paused indicates if the Oracle is currently paused
	Paused bool `protobuf:"varint,1,opt,name=paused,proto3" json:"paused,omitempty"`
	// paused_by is the address that triggered the pause
	PausedBy string `protobuf:"bytes,2,opt,name=paused_by,json=pausedBy,proto3" json:"paused_by,omitempty"`
	// pause_reason explains why the pause was triggered
	PauseReason string `protobuf:"bytes,3,opt,name=pause_reason,json=pauseReason,proto3" json:"pause_reason,omitempty"`
	// paused_at_height is the block height when pause was activated
	PausedAtHeight int64 `protobuf:"varint,4,opt,name=paused_at_height,json=pausedAtHeight,proto3" json:"paused_at_height,omitempty"`
}

func (m *EmergencyPauseState) Reset()         { *m = EmergencyPauseState{} }
func (m *EmergencyPauseState) String() string { return proto.CompactTextString(m) }
func (*EmergencyPauseState) ProtoMessage()    {}
func (*EmergencyPauseState) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bc0ab4b4862cbcd, []int{1}
}
func (m *EmergencyPauseState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EmergencyPauseState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EmergencyPauseState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EmergencyPauseState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmergencyPauseState.Merge(m, src)
}
func (m *EmergencyPauseState) XXX_Size() int {
	return m.Size()
}
func (m *EmergencyPauseState) XXX_DiscardUnknown() {
	xxx_messageInfo_EmergencyPauseState.DiscardUnknown(m)
}

var xxx_messageInfo_EmergencyPauseState proto.InternalMessageInfo

func (m *EmergencyPauseState) GetPaused() bool {
	if m != nil {
		return m.Paused
	}
	return false
}

func (m *EmergencyPauseState) GetPausedBy() string {
	if m != nil {
		return m.PausedBy
	}
	return ""
}

func (m *EmergencyPauseState) GetPauseReason() string {
	if m != nil {
		return m.PauseReason
	}
	return ""
}

func (m *EmergencyPauseState) GetPausedAtHeight() int64 {
	if m != nil {
		return m.PausedAtHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*CircuitBreakerState)(nil), "paw.oracle.v1.CircuitBreakerState")
	proto.RegisterType((*EmergencyPauseState)(nil), "paw.oracle.v1.EmergencyPauseState")
}

func init() { proto.RegisterFile("paw/oracle/v1/state.proto", fileDescriptor_1bc0ab4b4862cbcd) }

var fileDescriptor_1bc0ab4b4862cbcd = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xc1, 0x4e, 0xc2, 0x30,
	0x18, 0xc7, 0xa9, 0x20, 0x81, 0x02, 0xc6, 0x0c, 0x63, 0xa6, 0x26, 0x13, 0xf1, 0xe0, 0x2e, 0x6e,
	0x21, 0xde, 0xbc, 0x31, 0x63, 0xe2, 0xd1, 0x4c, 0x4f, 0x5e, 0x96, 0xae, 0x7c, 0xd9, 0x1a, 0x18,
	0x5d, 0xba, 0x32, 0xdc, 0x5b, 0xf8, 0x02, 0x26, 0x3e, 0x85, 0xcf, 0xe0, 0x91, 0xa3, 0x47, 0x03,
	0x17, 0x1f, 0xc3, 0xac, 0x05, 0x0c, 0xb7, 0xff, 0xff, 0xf7, 0xf5, 0x6b, 0x7e, 0x4d, 0xf1, 0x49,
	0x4a, 0xe6, 0x2e, 0x17, 0x84, 0x4e, 0xc0, 0xcd, 0x07, 0x6e, 0x26, 0x89, 0x04, 0x27, 0x15, 0x5c,
	0x72, 0xa3, 0x93, 0x92, 0xb9, 0xa3, 0x47, 0x4e, 0x3e, 0x38, 0x3d, 0x8a, 0x78, 0xc4, 0xd5, 0xc4,
	0x2d, 0x93, 0x3e, 0xd4, 0xff, 0x44, 0xb8, 0x7b, 0xc7, 0x04, 0x9d, 0x31, 0xe9, 0x09, 0x20, 0x63,
	0x10, 0x4f, 0xe5, 0x15, 0xc6, 0x31, 0xae, 0x13, 0x2a, 0x59, 0x0e, 0x26, 0xea, 0x21, 0xbb, 0xe1,
	0xaf, 0x9b, 0x71, 0x81, 0xdb, 0x52, 0xb0, 0x28, 0x02, 0x01, 0xa3, 0x20, 0x2c, 0xcc, 0xbd, 0x1e,
	0xb2, 0x9b, 0x7e, 0x6b, 0xcb, 0xbc, 0xa2, 0x5c, 0x15, 0x40, 0x32, 0x3e, 0x35, 0xab, 0x6a, 0xb8,
	0x6e, 0xe5, 0x6a, 0x38, 0xe1, 0x74, 0x1c, 0xc4, 0xc0, 0xa2, 0x58, 0x9a, 0xb5, 0x1e, 0xb2, 0xab,
	0x7e, 0x4b, 0xb1, 0x07, 0x85, 0x8c, 0x4b, 0xdc, 0x11, 0x40, 0x79, 0x0e, 0xa2, 0x08, 0x24, 0x4b,
	0xc0, 0xdc, 0x57, 0x67, 0xda, 0x1b, 0xf8, 0xcc, 0x12, 0xb8, 0xad, 0xfd, 0x7e, 0x9c, 0xa3, 0xfe,
	0x3b, 0xc2, 0xdd, 0xfb, 0x04, 0x44, 0x04, 0x53, 0x5a, 0x3c, 0x92, 0x59, 0x06, 0x5b, 0xf1, 0xb4,
	0x6c, 0xa3, 0x8d, 0xb8, 0x6e, 0xc6, 0x19, 0x6e, 0xea, 0xf4, 0x6f, 0xdd, 0xd0, 0xc0, 0x2b, 0x4a,
	0x35, 0x95, 0x83, 0x1d, 0xf1, 0x96, 0x62, 0xbe, 0xb6, 0xb7, 0xf1, 0xe1, 0x7a, 0x9f, 0xc8, 0xdd,
	0x17, 0x1c, 0x68, 0x3e, 0x94, 0xfa, 0x11, 0xda, 0xcf, 0x1b, 0x7e, 0x2d, 0x2d, 0xb4, 0x58, 0x5a,
	0xe8, 0x67, 0x69, 0xa1, 0xb7, 0x95, 0x55, 0x59, 0xac, 0xac, 0xca, 0xf7, 0xca, 0xaa, 0xbc, 0x5c,
	0x45, 0x4c, 0xc6, 0xb3, 0xd0, 0xa1, 0x3c, 0x71, 0x53, 0x32, 0xbf, 0xa6, 0x31, 0x61, 0xd3, 0x32,
	0xb9, 0xaf, 0x9b, 0x9f, 0x94, 0x45, 0x0a, 0x59, 0x58, 0x57, 0x5f, 0x74, 0xf3, 0x17, 0x00, 0x00,
	0xff, 0xff, 0x82, 0x10, 0x05, 0x63, 0xe4, 0x01, 0x00, 0x00,
}

func (this *CircuitBreakerState) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CircuitBreakerState)
	if !ok {
		that2, ok := that.(CircuitBreakerState)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Active != that1.Active {
		return false
	}
	if this.TriggeredBy != that1.TriggeredBy {
		return false
	}
	if this.Reason != that1.Reason {
		return false
	}
	if this.BlockHeight != that1.BlockHeight {
		return false
	}
	if this.RecoveryTime != that1.RecoveryTime {
		return false
	}
	return true
}
func (this *EmergencyPauseState) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EmergencyPauseState)
	if !ok {
		that2, ok := that.(EmergencyPauseState)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Paused != that1.Paused {
		return false
	}
	if this.PausedBy != that1.PausedBy {
		return false
	}
	if this.PauseReason != that1.PauseReason {
		return false
	}
	if this.PausedAtHeight != that1.PausedAtHeight {
		return false
	}
	return true
}
func (m *CircuitBreakerState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CircuitBreakerState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CircuitBreakerState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RecoveryTime != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.RecoveryTime))
		i--
		dAtA[i] = 0x28
	}
	if m.BlockHeight != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintState(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TriggeredBy) > 0 {
		i -= len(m.TriggeredBy)
		copy(dAtA[i:], m.TriggeredBy)
		i = encodeVarintState(dAtA, i, uint64(len(m.TriggeredBy)))
		i--
		dAtA[i] = 0x12
	}
	if m.Active {
		i--
		if m.Active {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EmergencyPauseState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EmergencyPauseState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EmergencyPauseState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PausedAtHeight != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.PausedAtHeight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.PauseReason) > 0 {
		i -= len(m.PauseReason)
		copy(dAtA[i:], m.PauseReason)
		i = encodeVarintState(dAtA, i, uint64(len(m.PauseReason)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.PausedBy) > 0 {
		i -= len(m.PausedBy)
		copy(dAtA[i:], m.PausedBy)
		i = encodeVarintState(dAtA, i, uint64(len(m.PausedBy)))
		i--
		dAtA[i] = 0x12
	}
	if m.Paused {
		i--
		if m.Paused {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintState(dAtA []byte, offset int, v uint64) int {
	offset -= sovState(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CircuitBreakerState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Active {
		n += 2
	}
	l = len(m.TriggeredBy)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovState(uint64(m.BlockHeight))
	}
	if m.RecoveryTime != 0 {
		n += 1 + sovState(uint64(m.RecoveryTime))
	}
	return n
}

func (m *EmergencyPauseState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Paused {
		n += 2
	}
	l = len(m.PausedBy)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.PauseReason)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.PausedAtHeight != 0 {
		n += 1 + sovState(uint64(m.PausedAtHeight))
	}
	return n
}

func sovState(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozState(x uint64) (n int) {
	return sovState(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CircuitBreakerState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CircuitBreakerState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CircuitBreakerState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Active = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TriggeredBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TriggeredBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecoveryTime", wireType)
			}
			m.RecoveryTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RecoveryTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EmergencyPauseState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EmergencyPauseState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EmergencyPauseState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Paused", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Paused = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PausedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PausedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PauseReason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PauseReason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PausedAtHeight", wireType)
			}
			m.PausedAtHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PausedAtHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipState(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowState
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthState
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupState
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthState
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthState        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowState          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupState = fmt.Errorf("proto: unexpected end of group")
)
