// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: paw/oracle/v1/tx.proto

package types

import (
	"context"
	math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	// github.com_cosmos_gogoproto_proto "github.com/cosmos/gogoproto/proto"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
// var _ = github.com_cosmos_gogoproto_proto.Marshal
var _ = grpc.ClientConn{}

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.GoGoProtoPackageIsVersion3

// MsgSubmitPrice submits a price feed update
type MsgSubmitPrice struct {
	Validator string         `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	Feeder    string         `protobuf:"bytes,2,opt,name=feeder,proto3" json:"feeder,omitempty"`
	Asset     string         `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	Price     math.LegacyDec `protobuf:"bytes,4,opt,name=price,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"price"`
}

func (m *MsgSubmitPrice) Reset()         { *m = MsgSubmitPrice{} }
func (m *MsgSubmitPrice) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitPrice) ProtoMessage()    {}

// MsgSubmitPriceResponse defines the response for MsgSubmitPrice
type MsgSubmitPriceResponse struct{}

func (m *MsgSubmitPriceResponse) Reset()         { *m = MsgSubmitPriceResponse{} }
func (m *MsgSubmitPriceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitPriceResponse) ProtoMessage()    {}

// MsgDelegateFeedConsent allows a validator to delegate price submission
type MsgDelegateFeedConsent struct {
	Validator string `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	Delegate  string `protobuf:"bytes,2,opt,name=delegate,proto3" json:"delegate,omitempty"`
}

func (m *MsgDelegateFeedConsent) Reset()         { *m = MsgDelegateFeedConsent{} }
func (m *MsgDelegateFeedConsent) String() string { return proto.CompactTextString(m) }
func (*MsgDelegateFeedConsent) ProtoMessage()    {}

// MsgDelegateFeedConsentResponse defines the response for MsgDelegateFeedConsent
type MsgDelegateFeedConsentResponse struct{}

func (m *MsgDelegateFeedConsentResponse) Reset()         { *m = MsgDelegateFeedConsentResponse{} }
func (m *MsgDelegateFeedConsentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDelegateFeedConsentResponse) ProtoMessage()    {}

// MsgUpdateParams updates the module parameters (governance only)
type MsgUpdateParams struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params    Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}

// MsgUpdateParamsResponse defines the response for MsgUpdateParams
type MsgUpdateParamsResponse struct{}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}

func init() {
	proto.RegisterType((*MsgSubmitPrice)(nil), "paw.oracle.v1.MsgSubmitPrice")
	proto.RegisterType((*MsgSubmitPriceResponse)(nil), "paw.oracle.v1.MsgSubmitPriceResponse")
	proto.RegisterType((*MsgDelegateFeedConsent)(nil), "paw.oracle.v1.MsgDelegateFeedConsent")
	proto.RegisterType((*MsgDelegateFeedConsentResponse)(nil), "paw.oracle.v1.MsgDelegateFeedConsentResponse")
	proto.RegisterType((*MsgUpdateParams)(nil), "paw.oracle.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "paw.oracle.v1.MsgUpdateParamsResponse")
}

func (m *MsgSubmitPrice) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitPrice) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitPrice) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	return 0, nil
}

func (m *MsgSubmitPrice) Size() (n int) {
	return 0
}

func (m *MsgSubmitPrice) Unmarshal(dAtA []byte) error {
	return nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}

func (m *MsgSubmitPrice) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return m.Marshal()
}
func (m *MsgSubmitPrice) XXX_Merge(src proto.Message) {
}
func (m *MsgSubmitPrice) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitPrice) XXX_DiscardUnknown() {
}

var xxx_messageInfo_MsgSubmitPrice proto.InternalMessageInfo

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SubmitPrice(context.Context, *MsgSubmitPrice) (*MsgSubmitPriceResponse, error)
	DelegateFeedConsent(context.Context, *MsgDelegateFeedConsent) (*MsgDelegateFeedConsentResponse, error)
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
}

type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SubmitPrice(ctx context.Context, req *MsgSubmitPrice) (*MsgSubmitPriceResponse, error) {
	return nil, nil
}

func (*UnimplementedMsgServer) DelegateFeedConsent(ctx context.Context, req *MsgDelegateFeedConsent) (*MsgDelegateFeedConsentResponse, error) {
	return nil, nil
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, nil
}

// Service descriptor
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "paw.oracle.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitPrice",
			Handler:    nil,
		},
		{
			MethodName: "DelegateFeedConsent",
			Handler:    nil,
		},
		{
			MethodName: "UpdateParams",
			Handler:    nil,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paw/oracle/v1/tx.proto",
}

// RegisterMsgServer registers the Msg service
func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}
